<?xml version="1.0"?>
<!-- weathersensor data -->
<!-- $Id: wdata.xml,v 1.2 2002/03/27 08:33:30 jahns Exp jahns $ -->
<!DOCTYPE weatherReportList [
  <!ELEMENT weatherReportList (weatherReport*)>
  <!ELEMENT weatherReport (time, date, timeAlarm?, units, outdoorTemperature?,
outdoorHumidity?, indoorTemperature?, indoorHumidity?, barometricPressure?, wind?, rain? )>  
  <!ATTLIST weatherReport stationId CDATA #REQUIRED>

  <!ELEMENT time (#PCDATA)>
  <!ELEMENT date (#PCDATA)>
  <!ELEMENT timeAlarm (#PCDATA)>
  <!ELEMENT units (#PCDATA)>

  <!ELEMENT outdoorTemperature 
   (
     average, high?, low?, dewpoint?, 
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST outdoorTemperature Id CDATA #REQUIRED>

  <!ELEMENT outdoorHumidity 
   (
     average, high?, low?, dewpoint?, 
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST outdoorHumidity Id CDATA #REQUIRED>

  <!ELEMENT indoorTemperature 
   (
     average, high?, low?, dewpoint?, 
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST indoorTemperature Id CDATA #REQUIRED>

  <!ELEMENT indoorHumidity 
   (
     average, high?, low?, dewpoint?, 
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST indoorHumidity Id CDATA #REQUIRED>

  <!ELEMENT barometricPressure 
   (
     local, sealevel?, tendency?,
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST barometricPressure Id CDATA #REQUIRED>

  <!ELEMENT wind 
   (
     averageSpeed, averageDirection, medianDeviation?,
     gustSpeed?, gustDirection?, highSpeed?, highDirection?,
     chill?,
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST wind Id CDATA #REQUIRED>
  <!ELEMENT rain 
   (
     total, rate?, yesterday?,
     batteryStatus?, alarmSet?, receiveErr?
   )>
    <!ATTLIST rain Id CDATA #REQUIRED>

  <!-- all temperature and humidity -->
  <!ELEMENT average (#PCDATA)>
  <!ELEMENT high (#PCDATA)>
  <!ELEMENT low (#PCDATA)>
  <!ELEMENT dewpoint (#PCDATA)> 

  <!-- barometricPressure -->
  <!ELEMENT local (#PCDATA)>
  <!ELEMENT sealevel (#PCDATA)>
  <!ELEMENT tendency (#PCDATA)>
 
  <!-- wind -->
  <!ELEMENT averageSpeed (#PCDATA)>
  <!ELEMENT averageDirection (#PCDATA)>
  <!ELEMENT medianDeviation (#PCDATA)>
  <!ELEMENT gustSpeed (#PCDATA)>
  <!ELEMENT gustDirection (#PCDATA)>
  <!ELEMENT highSpeed (#PCDATA)>
  <!ELEMENT highDirection (#PCDATA)>
  <!ELEMENT chill (#PCDATA)>
  <!-- rain -->
  <!ELEMENT total (#PCDATA)>
  <!ELEMENT rate (#PCDATA)>
  <!ELEMENT yesterday (#PCDATA)>
  <!-- general for all sensors -->
  <!ELEMENT batteryStatus (#PCDATA)>
  <!ELEMENT alarmSet (#PCDATA)>
  <!ELEMENT receiveErr (#PCDATA)>
]>


<!-- xml data from here -->
<weatherReportList>
 <weatherReport stationId="1">
  <time> </time>
  <date> </date>
  <timeAlarm> </timeAlarm>
  <units>SI</units>

  <outdoorTemperature Id="1" >
    <average>11.5</average>
    <high>15.4 </high>
    <low>7.2</low>
    <dewpoint>10.5</dewpoint>
    <batteryStatus>low</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>0</receiveErr>
  </outdoorTemperature>

  <outdoorHumidity Id="1">
    <average>54.5</average>
    <high>55.0</high>
    <low>52.7</low>
    <dewpoint>10.5</dewpoint>
    <batteryStatus>low</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>1</receiveErr>
  </outdoorHumidity>

  <indoorTemperature Id="1">
    <average>17.5</average>
    <high>18.4</high>
    <low>17.0</low>
    <dewpoint>11.5</dewpoint>
    <batteryStatus>high</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>0</receiveErr>
  </indoorTemperature>

  <indoorHumidity Id="1">
    <average>40.0</average>
    <high>42.3</high>
    <low>39.2</low>
    <dewpoint>11.5</dewpoint>
    <batteryStatus>low</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>3</receiveErr>
  </indoorHumidity>

  <barometricPressure Id="1">
    <local>752</local>
    <sealevel>1013</sealevel>
    <tendency>rising</tendency>
    <batteryStatus>low</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>1</receiveErr>
  </barometricPressure>

  <wind Id="1">
    <averageSpeed>2.5</averageSpeed>
    <averageDirection>315</averageDirection>
    <medianDeviation>22.5</medianDeviation>
    <gustSpeed>5.0</gustSpeed>
    <gustDirection>300</gustDirection>
    <highSpeed>6.0</highSpeed>
    <highDirection>310</highDirection>
    <chill>9.5</chill>
    <batteryStatus>low</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>1</receiveErr>    
  </wind>

  <rain Id="1">
    <total>987</total>
    <rate>0</rate>
    <yesterday>3</yesterday>
    <batteryStatus>low</batteryStatus>
    <alarmSet>off</alarmSet>
    <receiveErr>0</receiveErr>
  </rain>

 </weatherReport>
</weatherReportList>


