<?xml version="1.0"?>
<!-- weathersensor data -->
<!-- $Id: wdata.xml,v 1.2 2002/03/27 08:33:30 jahns Exp jahns $ -->
<!DOCTYPE weatherReportList [
  <!ELEMENT weatherReportList (weatherReport*)>
  <!ELEMENT weatherReport (time, date, timeAlarm?, units )>  
    <!ATTLIST weatherReport stationId CDATA #REQUIRED>
  <!ELEMENT time (#PCDATA)>
  <!ELEMENT date (#PCDATA)>
  <!ELEMENT timeAlarm (#PCDATA)>
  <!ELEMENT units (#PCDATA)>
]>


<!-- xml data from here -->
<weatherReportList>
 <weatherReport stationId="1">
  <time> </time>
  <date> </date>
  <timeAlarm> </timeAlarm>
  <units>SI</units>

 </weatherReport>
</weatherReportList>

